### ISSUE TITLE
`rudric init` results in error returned from database: (code: 14) unable to open database file

### ISSUE THREAD

**Issue by Somfic** [mike-lloyd03/rudric#86]
Hi,

When getting started and running `rudric init` i’m getting this error:

```
Error: error: error returned from database: (code: 14) unable to open database file
```

Also tried running with sudo but no luck. I’m on a MacBook.

**Comment by mike-lloyd03** [comment]
Hey thanks for finding a glaring error. I forgot to create the config directory if it doesn't exist.

Fixed by 0166712fff738b0ff8d3604bcfeeb01f846368ef

A new release is being pushed out now.
